name: Docker Image CI

on:
  push:
    branches: [ fix ]
    tags: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0.1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: zodd31 # optional
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          # Docker repository to tag the image with
          repository: zodd31/wiki-dsna
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          # tags: # optional
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true # optional
          # Path to the build context
          path: ./Dockerfile # optional, default is .
